### ISSUE TITLE
Where did you sleep last night - vulnerability 

### ISSUE THREAD

**Issue by andreaNCCEH** [timbender-ncceh/ce_assessment#1]
On our vulnerability response ranking order looks like Sheltered was scored higher than Unsheltered. The more vulnerable response should be unsheltered. 
<img width="452" alt="Correct ranking" src="https://github.com/timbender-ncceh/ce_assessment/assets/67340114/2dad1bfb-188b-484d-9993-02190ad3a3c2">

**Comment by timbender-ncceh** [comment]
![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/e28da525-f16e-432a-855f-c5f300b5ac96)
 
fixed this and one other.
