### ISSUE TITLE
Filter for top 20% scores

### ISSUE THREAD

**Issue by andreaNCCEH** [timbender-ncceh/ce_assessment#2]
I'd like to be able to answer the question, what is the racial and ethnic distribution of points for the Top 20% of scores under any scenario. This will help the Core Team evaluate the ranking options against the team's goal of 43% of the top 20% of scores identifying proportionately as Black.

**Comment by timbender-ncceh** [comment]
The goal; the final outcome sorted list - will show (ideally) the top 20% of clients being 43% Black by Race.  @timbender-ncceh

**Comment by timbender-ncceh** [comment]
RACE: 
![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/89ff9dab-6d8d-40a8-864e-fc4b363152d5)

![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/f3954ef8-fa5c-4736-8836-4c15c3bd411f)

**Comment by timbender-ncceh** [comment]
@andreaNCCEH I think your answers are now included above in comments.
