### ISSUE TITLE
Several tiny methodology Issues to Clean

### ISSUE THREAD

**Issue by timbender-ncceh** [timbender-ncceh/ce_assessment#4]
Example proper (and simple) model for use as reference: https://or.stackexchange.com/questions/7835/use-the-weighted-sum-method-in-r

Some example changes to make: 
![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/5a09cf73-f0c6-4d33-b032-970c6c664231)

# Starting Dataset: 
![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/3ef6f015-b4dc-406b-858c-e9ab24d5d769)

# Convert Letter Grade to Integer Value:
![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/978cf8ca-66ef-4f2d-b607-76321a986e53)

# Assign Weight Values: 
![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/f8f53294-24bb-46d3-af71-fe99090442f6)

# Scale Dataset: 
![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/c4b8787b-e6eb-4ec1-9407-c6757e6bd7cb)

# Score and Rank: 
![image](https://github.com/timbender-ncceh/ce_assessment/assets/105810134/7a779751-51d5-4fce-a6a3-5ebb2dfe2f1c)

**Comment by andreaNCCEH** [comment]
I've added normalized ranking in Response Vulnerability tab of this spreadsheet: https://ncceh.sharepoint.com/:x:/s/boscoccoordination/EbaXcHJZpX1Dirf1Ql7u_9YB5FTYsxfbI5uEmPHm2Z8zjg?e=I7dYbc
